name:                QuadCI
version:             0.1.0.0
github:              "githubuser/QuadCI"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/QuadCI#readme>

dependencies:
- aeson
- async
- base
#- bytestring
- butcher
- hslogger
- hspec
- http-client
- http-conduit
- http-types
- network
- record-hasfield
- rio
- scotty
- serialise
- stm
- time
#- text
- typed-process
- wai-cors
- yaml
#- docker
- process


ghc-options:
- -F -pgmF=record-dot-preprocessor  
- -fprint-potential-instances

library:
  source-dirs: src

executables:
  QuadCI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuadCI

tests:
  QuadCI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuadCI

default-extensions:
- BlockArguments
- DeriveAnyClass
- DeriveGeneric
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- StrictData
- NamedFieldPuns